
# prod
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://my.nalpari.net:33306/test?characterEncoding=UTF-8&serverTimezone=UTC
    hikari:
      username: jaeuchoi
      password: qwer1234
server:
  port : 29090
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /

jpa: #JPA 설정
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true